name: Documentation Generation
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.py"

permissions:
  contents: write

jobs:
  doc-generation:
    name: Documentation Generation
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
      - name: "Generate docs"
        run: |
          pip3 install setup.py
          make gen-docs
          mkdocs gh-deploy --force --clean
          mv sources docs
      - name: "Commit generated documentation"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Updating documentation"